<?php
/**
 * @file
 * morgans_test.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function morgans_test_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-ctda-contextual-menu_about-:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive.
  $menu_links['menu-ctda-contextual-menu_about-:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    'router_path' => '',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_about-:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_community-members--:https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members.
  $menu_links['menu-ctda-contextual-menu_community-members--:https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members',
    'router_path' => '',
    'link_title' => 'Community Members | ',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_community-members--:https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_ctda-technology-:https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology.
  $menu_links['menu-ctda-contextual-menu_ctda-technology-:https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology',
    'router_path' => '',
    'link_title' => 'CTDA Technology |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_ctda-technology-:https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -4,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_join:https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA.
  $menu_links['menu-ctda-contextual-menu_join:https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA',
    'router_path' => '',
    'link_title' => 'Join',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_join:https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -2,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_people-of-ctda-:https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA.
  $menu_links['menu-ctda-contextual-menu_people-of-ctda-:https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA',
    'router_path' => '',
    'link_title' => 'People of CTDA |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_people-of-ctda-:https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -6,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-information_about-the-ctda:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive.
  $menu_links['menu-ctda-information_about-the-ctda:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive'] = array(
    'menu_name' => 'menu-ctda-information',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    'router_path' => '',
    'link_title' => 'About the CTDA',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-information_about-the-ctda:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('About the CTDA');
  t('About |');
  t('CTDA Technology |');
  t('Community Members | ');
  t('Join');
  t('People of CTDA |');

  return $menu_links;
}
